# Generated by Django 2.2.5 on 2020-02-03 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='direction',
            field=models.TextField(default='Text Here'),
        ),
        migrations.AddField(
            model_name='items',
            name='ingredients',
            field=models.TextField(default='Text Here'),
        ),
        migrations.AddField(
            model_name='items',
            name='servings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='time',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
            preserve_default=False,
        ),
    ]
