# Generated by Django 2.2.5 on 2020-02-04 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200203_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='time',
            field=models.CharField(default='1 Min', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
