# Generated by Django 2.2.5 on 2020-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_items_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
