# Generated by Django 2.2.5 on 2020-02-27 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cooking_time',
            field=models.CharField(default='1 Min', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='items',
            name='direction',
            field=models.TextField(default='Text Here', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='items',
            name='ingredients',
            field=models.TextField(default='Text Here', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='items',
            name='preparation_time',
            field=models.CharField(default='1 Min', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')]),
        ),
    ]
