# Generated by Django 2.2.5 on 2020-02-04 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200204_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='direction',
            field=models.TextField(default='Text Here', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='items',
            name='ingredients',
            field=models.TextField(default='Text Here', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
