# Generated by Django 2.2.5 on 2020-02-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200227_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
    ]
