# Generated by Django 2.2.5 on 2020-02-05 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200204_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='time',
        ),
        migrations.AddField(
            model_name='items',
            name='cooking_time',
            field=models.CharField(default='1 Min', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='items',
            name='preparation_time',
            field=models.CharField(default='1 Min', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
