# Generated by Django 2.2.5 on 2020-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200205_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='food_image',
            field=models.ImageField(upload_to='food_pic'),
        ),
        migrations.AlterField(
            model_name='items',
            name='profile_pic',
            field=models.ImageField(upload_to='Profile_pic'),
        ),
    ]
