# Generated by Django 2.2.5 on 2020-02-28 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_items_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.TextField(default='Tell us about yourself', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')])),
                ('facebook', models.CharField(default='Facebook Account', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')])),
                ('twitter', models.CharField(default='Twitter Account', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')])),
                ('website', models.CharField(default='www.example.com', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$')])),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Items')),
            ],
        ),
    ]
