# Generated by Django 2.2.5 on 2020-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200206_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='food_pic'),
        ),
        migrations.AlterField(
            model_name='items',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Profile_pic'),
        ),
    ]
