# Generated by Django 2.2.5 on 2020-02-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_author_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
