# Generated by Django 2.2.5 on 2020-02-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_items_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Items')),
            ],
        ),
        migrations.DeleteModel(
            name='Author_Page',
        ),
    ]
