# Generated by Django 2.2.5 on 2020-02-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200217_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_page',
            old_name='items_list',
            new_name='item_type_list',
        ),
    ]
